name: projetofinalflutter
description: Um aplicativo de gerenciamento de tarefas desenvolvido em Flutter.
publish_to: 'none' # Define como 'none' para indicar que o pacote não será publicado no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5 # Adicione esta linha

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/list.png
